apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gaia
  labels:
    app: gaia
spec:
  selector:
    matchLabels:
      app: gaia
  serviceName: gaia
  replicas: 1
  template:
    metadata:
      labels:
        app: gaia
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-cosmos-claim
      containers:
      - name: gaia
        image: larryannon/cosmos-gaia:v17.3.0
        resources:
          requests:
            memory: "16Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "2"
        ports:
        - containerPort: 26656
          name: p2p
        - containerPort: 26657
          name: rpc
        - containerPort: 26660
          name: metrics
        volumeMounts:
        - name: task-pv-storage
          mountPath: /gaia/.gaia
  # volumeClaimTemplates:
  # - metadata:
  #     name: gaia-data
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     resources:
  #       requests:
  #         storage: 10Gi