- name: Copy cosmos-gaia to master node
  ansible.builtin.copy:
    src: files/*.yml
    dest: "{{ k8s_apply_cosmos_file }}/gaia"
    mode: '0644'

- name: Apply cosmos-gaia
  ansible.builtin.shell: |
    kubectl apply -f {{ k8s_apply_cosmos_file }}/gaia 
  register: apply_output