---
- name: Install containerd
  block:

    - name: Add docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor  --yes -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker APT repository
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update APT cache
      apt:
        update_cache: yes
   
    - name: Install containerd
      apt:
        name: containerd.io=1.6.25-1
        state: present

    - name: Configure containerd
      template:
        src: containerd-config.toml.j2
        dest: /etc/containerd/config.toml
      notify:
        - Restart containerd

- name: Start and enable containerd
  systemd:
    name: containerd
    state: started
    enabled: yes

- name: Configure kubelet to use containerd
  ansible.builtin.lineinfile:
    path: /var/lib/kubelet/kubeadm-flags.env
    line: KUBELET_EXTRA_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --cgroup-driver=systemd"
    create: yes
  notify:
    - Restart kubelet

